### ISSUE TITLE
Named parameters generate error exception when used with returned function

### ISSUE THREAD

**Issue by k33g** [eclipse/golo-lang#335]
Named parameters generate error exception when used with returned function:

With this sample:
```golo
function yo = |message| {
  return |before, after| {
    println(before + ":" + message + ":" + after)
  }
}

function main = |args| {
  yo("bob")("Hello", "!") #Hello:bob:!
  yo("sam")(before="Hello", after="!")
}
```

`yo("sam")(before="Hello", after="!")` throw an IllegalAccessException:

    Exception in thread "main" java.lang.IllegalAccessException: no such method: named_params.main(String[])void/invokeStatic
            at java.lang.invoke.MemberName.makeAccessException(MemberName.java:872)
            at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:993)
            at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1379)
            at java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:776)
            at org.eclipse.golo.cli.command.spi.CliCommand.callRun(CliCommand.java:39)
            at org.eclipse.golo.cli.command.GoloGoloCommand.execute(GoloGoloCommand.java:54)
            at org.eclipse.golo.cli.Main.main(Main.java:64)
    Caused by: java.lang.VerifyError: Operand stack underflow
    Exception Details:
      Location:
        named_params.main([Ljava/lang/String;)V @30: invokedynamic
      Reason:
        Attempt to pop empty stack.
      Current Frame:
        bci: @30
        flags: { }
        locals: { '[Ljava/lang/String;' }
        stack: { 'gololang/FunctionReference' }
      Bytecode:
        0x0000000: 1231 ba00 3900 00c0 0027 123b 123d ba00
        0x0000010: 4500 0057 1247 ba00 3900 00c0 0027 ba00
        0x0000020: 4500 0057 01b1
    
            at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
            at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:965)
            at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:990)
            ... 5 more

Strangely, if I reverse the 2 lines:
```golo
function main = |args| {
  yo("sam")(before="Hello", after="!")
  yo("bob")("Hello", "!") #Hello:bob:!
}
```

I get a different exception:

    Exception in thread "main" java.lang.NegativeArraySizeException
            at org.objectweb.asm.Frame.a(Unknown Source)
            at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source)
            at org.eclipse.golo.compiler.JavaBytecodeGenerationGoloIrVisitor.visitFunction(JavaBytecodeGenerationGoloIrVisitor.java:333)
            at org.eclipse.golo.compiler.ir.GoloFunction.accept(GoloFunction.java:333)
            at org.eclipse.golo.compiler.ir.GoloModule.walk(GoloModule.java:187)
            at org.eclipse.golo.compiler.JavaBytecodeGenerationGoloIrVisitor.visitModule(JavaBytecodeGenerationGoloIrVisitor.java:128)
            at org.eclipse.golo.compiler.ir.GoloModule.accept(GoloModule.java:163)
            at org.eclipse.golo.compiler.JavaBytecodeGenerationGoloIrVisitor.generateBytecode(JavaBytecodeGenerationGoloIrVisitor.java:82)
            at org.eclipse.golo.compiler.GoloCompiler.compile(GoloCompiler.java:102)
            at org.eclipse.golo.compiler.GoloClassLoader.load(GoloClassLoader.java:53)
            at org.eclipse.golo.cli.command.GoloGoloCommand.loadGoloFile(GoloGoloCommand.java:75)
            at org.eclipse.golo.cli.command.GoloGoloCommand.execute(GoloGoloCommand.java:45)
            at org.eclipse.golo.cli.Main.main(Main.java:64)

**Comment by jponge** [comment]
Are you still having the issue?

**Comment by k33g** [comment]
yes

**Comment by yloiseau** [comment]
This seams to appear only when using anonymous call. Indeed:
```golo
let y = yo("sam")
y(before="Hello", after="!")
```
is OK.

**Comment by yloiseau** [comment]
On the other hand:
```golo
function say = |message, before, after| {
  println(before + ":" + message + ":" + after)
}

function main = |args| {
  ^say: bindAt("message", "sam")(before="Hello", after="!")
}
```

throws the same exception, only if using named arguments.
The issue should thus be located at the conjunction of anonymous call and named arguments :smile:

**Comment by yloiseau** [comment]
Moreover, it's a compile time error.

**Comment by yloiseau** [comment]
It's actually when named arguments are used on references:
```golo
module Test
function add = |left, right| -> left + right
function main = |args| {
  ^add(right="a", left="b")
}
```

```
$ golo golo --files test.golo 
Exception in thread "main" java.lang.IllegalAccessException: no such method: TestA.main(String[])void/invokeStatic
	at java.lang.invoke.MemberName.makeAccessException(MemberName.java:869)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:990)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1382)
	at java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:777)
	at org.eclipse.golo.cli.command.spi.CliCommand.callRun(CliCommand.java:39)
	at org.eclipse.golo.cli.command.GoloGoloCommand.execute(GoloGoloCommand.java:54)
	at org.eclipse.golo.cli.Main.main(Main.java:64)
Caused by: java.lang.VerifyError: Operand stack underflow
Exception Details:
  Location:
    TestA.main([Ljava/lang/String;)V @19: invokedynamic
  Reason:
    Attempt to pop empty stack.
  Current Frame:
    bci: @19
    flags: { }
    locals: { '[Ljava/lang/String;' }
    stack: { 'gololang/FunctionReference' }
  Bytecode:
    0x0000000: 1228 ba00 3100 0002 b800 37ba 0042 0000
    0x0000010: c000 44ba 004d 0000 5701 b1            

	at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:962)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:987)
	... 5 more
```

Arguments are not pushed to the stack:
```java
  public static void main(java.lang.String[]);
    descriptor: ([Ljava/lang/String;)V
    flags: ACC_PUBLIC, ACC_STATIC
    Code:
      stack=3, locals=1, args_size=1
         0: ldc           #40                 // String add
         2: invokedynamic #49,  0             // InvokeDynamic #1:Test:()Ljava/lang/Class;
         7: iconst_m1
         8: invokestatic  #55                 // Method java/lang/Integer.valueOf:(I)Ljava/lang/Integer;
        11: invokedynamic #66,  0             // InvokeDynamic #2:"gololang#Predefined#fun":(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
        16: checkcast     #68                 // class gololang/FunctionReference
        19: invokedynamic #77,  0             // InvokeDynamic #3:anonymous:(Lgololang/FunctionReference;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
        24: pop
        25: aconst_null
        26: return
```

while not using names (i.e. `^add("a", "b")`) generates:
```java
  public static void main(java.lang.String[]);
    descriptor: ([Ljava/lang/String;)V
    flags: ACC_PUBLIC, ACC_STATIC
    Code:
      stack=3, locals=1, args_size=1
         0: ldc           #40                 // String add
         2: invokedynamic #49,  0             // InvokeDynamic #1:Test:()Ljava/lang/Class;
         7: iconst_m1
         8: invokestatic  #55                 // Method java/lang/Integer.valueOf:(I)Ljava/lang/Integer;
        11: invokedynamic #66,  0             // InvokeDynamic #2:"gololang#Predefined#fun":(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
        16: checkcast     #68                 // class gololang/FunctionReference
        19: ldc           #70                 // String a
        21: ldc           #72                 // String b
        23: invokedynamic #81,  0             // InvokeDynamic #3:anonymous:(Lgololang/FunctionReference;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
        28: pop
        29: aconst_null
        30: return

```

**Comment by yloiseau** [comment]
Got it :tada:
