### ISSUE TITLE
Method resolution fails with other Java Frameworks (sometimes) 

### ISSUE THREAD

**Issue by k33g** [eclipse/golo-lang#405]
golo version: 3.2.0

This is 2 times that I have theses problems: (perhaps these are not linked :confused:)
- `java.lang.NoSuchMethodError` -> can't find the method
- `java.lang.ClassCastException` -> can't find the method with the good signature
## With Jedis

https://github.com/xetorthio/jedis

my golo code is simple (and has already worked in former versions):

``` golo
module play_with_jedis

import redis.client.jedis.Jedis

function main = |args| {
  let rdb = Jedis("localhost", 6379)
}
```

I get this error:

```
Exception in thread "main" java.lang.NoSuchMethodError: Jedis(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
    at org.eclipse.golo.runtime.FunctionCallSupport.fallback(FunctionCallSupport.java:149)
    at play_with_jedis_2.main(try.golo:8)
    at org.eclipse.golo.cli.command.spi.CliCommand.callRun(CliCommand.java:40)
    at org.eclipse.golo.cli.command.GoloGoloCommand.execute(GoloGoloCommand.java:55)
    at org.eclipse.golo.cli.Main.main(Main.java:62)
```
## With Vert.x

my golo code is simple (and has already worked in former versions):

``` golo
module webapp

import io.vertx.core.Vertx
import io.vertx.core.http.HttpServer
import io.vertx.ext.web.Router
import io.vertx.ext.web.handler

let vertx = Vertx.vertx()

function createHttpServer = {
  return vertx: createHttpServer()
}

function getRouter = {
  let router = Router.router(vertx)
  router: route(): handler(BodyHandler.create())
  return router
}

function startHttpServer = |server, router, port, staticPath| {
  router: route(staticPath): handler(StaticHandler.create())
  server: requestHandler(|httpRequest| -> router: accept(httpRequest)): listen(port)
  println("HttpServer is listening on " + port)
  return server
}

function main = |args| {
  let server = createHttpServer()
  let router = getRouter()

  router: get("/hello"): handler(|context| {

    let response = context: response()
    response: putHeader("content-type", "application/json")
    response: end(JSON.stringify(
      DynamicObject(): message("Hello :earth_africa: at JDD 2016")
    ))
  })

  startHttpServer(
    server=server,
    router=router,
    port=9090,
    staticPath="/*"
  )
}
```

I get this error:

```
java.lang.ClassCastException: java.lang.String cannot be cast to io.vertx.core.buffer.Buffer
    at io.vertx.core.http.impl.HttpServerResponseImpl.end(HttpServerResponseImpl.java:52)
    at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
    at org.eclipse.golo.runtime.MethodInvocationSupport.fallback(MethodInvocationSupport.java:280)
    at webapp.__$$_sugar_closure_2(golox.golo:47)
    at java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:187)
    at com.sun.proxy.$Proxy4.handle(Unknown Source)
    at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:221)
    at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78)
    at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:93)
    at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:155)
    at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:141)
    at io.vertx.ext.web.handler.impl.BodyHandlerImpl.lambda$handle$34(BodyHandlerImpl.java:61)
    at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:406)
    at io.vertx.core.http.impl.ServerConnection.handleEnd(ServerConnection.java:286)
    at io.vertx.core.http.impl.ServerConnection.processMessage(ServerConnection.java:404)
    at io.vertx.core.http.impl.ServerConnection.handleMessage(ServerConnection.java:134)
    at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:514)
    at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:420)
    at io.vertx.core.http.impl.VertxHttpHandler.lambda$channelRead$18(VertxHttpHandler.java:80)
    at io.vertx.core.impl.ContextImpl.lambda$wrapTask$16(ContextImpl.java:333)
    at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:225)
    at io.vertx.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:80)
    at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:124)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Thread.java:745)
```

the `end()` method on `HttpServerResponse` is overloaded:
- `end()`
- `end(String)`
- `end(Buffer)`

I want to call `end` with a `String`, but "something" want to call it with `Buffer`

❤️

**Comment by Artpej** [comment]
I think this should solve the first one: `Jedis("localhost", intValue(6379))`

**Comment by k33g** [comment]
@Artpej same issue with `intValue`

**Comment by k33g** [comment]
For each case, I had made the tests in a VM with Ubuntu and on my laptop with OSX

**Comment by Artpej** [comment]
@k33g my bad, Ii didn't see that Jedis also have this constructor: `Jedis(final URI uri, final int timeout)`

Unfortunately this one seems to be related to  #326 for both cases and I don't have any workaround for instance...

**Comment by k33g** [comment]
@Artpej  at least I'm not mad :stuck_out_tongue_winking_eye:

**Comment by yloiseau** [comment]
Did you try  `import redis.client.jedis` ?

**Comment by k33g** [comment]
@yloiseau same issue even with `let rdb = redis.client.jedis.Jedis("localhost", 6379)`

**Comment by yloiseau** [comment]
So I think @Artpej has the right answer

**Comment by yloiseau** [comment]
This is probably because it's `redis.clients.jedis` and not `redis.client.jedis` :smile:
However, It could be really valuable to print a warning if we import a package of class that is not found in the classpath, instead of simply saying that a call failed because the method is not found!

**Comment by k33g** [comment]
@yloiseau ouch 🙇  🤒  sorry
I'm going to test Vertx

**Comment by yloiseau** [comment]
Never mind... At least that raised an issue on the clarity of the error messages :smile:

**Comment by k33g** [comment]
And my tests are ok with Vert-x cc @Artpej 
👏

**Comment by jponge** [comment]
Great idea :-)
