### ISSUE TITLE
arrayTypeOf(byte.class) yields a ClassNotFoundException

### ISSUE THREAD

**Issue by utybo** [eclipse/golo-lang#479]
Everything is in the title. `arrayTypeOf(byte.class)` yields a `ClassNotFoundException` when one would expect it to return the Java equivalent of `byte[].class`

```
Exception in thread "main" java.lang.ClassNotFoundException: [Lbyte;
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at gololang.Predefined.arrayTypeOf(Predefined.java:613)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.eclipse.golo.runtime.FunctionCallSupport.fallback(FunctionCallSupport.java:195)
	at MyModule.main(main.golo:7)
	at org.eclipse.golo.cli.command.spi.CliCommand.callRun(CliCommand.java:53)
	at org.eclipse.golo.cli.command.GoloGoloCommand.execute(GoloGoloCommand.java:59)
	at org.eclipse.golo.cli.Main.main(Main.java:69)
```

**Comment by Artpej** [comment]
Good catch! A fix will coming soon...

**Comment by yloiseau** [comment]
Same bug with any primitive type…
