### ISSUE TITLE
NullPointerException with gololang.EvaluationEnvironment() when `\n` before the closure

### ISSUE THREAD

**Issue by k33g** [eclipse/golo-lang#509]
### first

```golo
let source = """# hello
|param| -> 40 + param
"""

function main = |args| {
  println(gololang.EvaluationEnvironment(): def(source)(2))
}
```

> it displays 42

### now ...

- I add a `\n`
- I add an other comment

```golo
let source = """# hello

# an other comment
|param| -> 40 + param
"""

function main = |args| {
  println(gololang.EvaluationEnvironment(): def(source)(2))
}
```

I get an exception:

```
Exception in thread "main" java.lang.NullPointerException
        at org.eclipse.golo.runtime.ClosureCallSupport.fallback(ClosureCallSupport.java:84)
        at sandbox.main(sandbox.golo:11)
        at org.eclipse.golo.cli.command.spi.CliCommand.callRun(CliCommand.java:39)
        at org.eclipse.golo.cli.command.GoloGoloCommand.execute(GoloGoloCommand.java:57)
        at org.eclipse.golo.cli.Main.main(Main.java:69)
```

if I remove the blank line, I keep the exception

```golo
let source = """# hello
# an other comment
|param| -> 40 + param
"""

function main = |args| {
  println(gololang.EvaluationEnvironment(): def(source)(2))
}
```

```
Exception in thread "main" java.lang.NullPointerException
        at org.eclipse.golo.runtime.ClosureCallSupport.fallback(ClosureCallSupport.java:84)
        at sandbox.main(sandbox.golo:10)
        at org.eclipse.golo.cli.command.spi.CliCommand.callRun(CliCommand.java:39)
        at org.eclipse.golo.cli.command.GoloGoloCommand.execute(GoloGoloCommand.java:57)
        at org.eclipse.golo.cli.Main.main(Main.java:69)
```

**Comment by Artpej** [comment]
It seems to be a parser issue:

```golo
module test

function main = |args| {
  println(response(2))
}

function response = |param| {
  return #test
  # a comment
  40 + param
}
```
prints `null`

```golo
module test

function main = |args| {
  println(response(2))
}

function response = |param| {
  return #test
  40 + param
}
```
works as expected...

@k33g  I can have a look if you want...

**Comment by yloiseau** [comment]
Incredible, we managed to have a JS semicolon bug without having semicolon in the grammar! 😂

**Comment by yloiseau** [comment]
More seriously, I'm not sure of what should be the correct behavior here. I'd say that the "correct" code is a bug, since without parens/braces/... the comment should end the expression.

**Comment by Artpej** [comment]
PR just landed : #510

**Comment by Artpej** [comment]
> the comment should end the expression

the more @yloiseau is older, the more picky he become :wink: 

Happy birthday mate! :tada: :cake: :clinking_glasses:

**Comment by k33g** [comment]
🎂  @yloiseau

**Comment by yloiseau** [comment]
Thanks guys

**Comment by jponge** [comment]
Oh happy birthday @yloiseau !!!

**Comment by jponge** [comment]
(rewind time 2 days ago)
